# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-31 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usermodelk1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('english', models.IntegerField()),
                ('computer', models.IntegerField()),
            ],
        ),
    ]
